---
- name: (Deian) remove old packages
  apt:
    name: "{{packages}}"
    state: absent
  vars:
    packages:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: (Deian) install required packages
  apt:
    name: "{{packages}}"
    state: present
  vars:
    packages:
    - apt-transport-https

- name: (Deian) add docker apt key
  apt_key:
    url: https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg
    state: present

- name: (Deian) add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution | lower}} {{ansible_distribution_release}} {{docker_channel}}
    filename: docker-ce
    state: present

- name: (Deian) install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: enable_docker

- name: (Deian) add users to docker group
  user:
    user:   "{{item}}"
    groups: "docker"
    append: yes
  loop: "{{docker_users}}"
