---
- name: (Deian) remove old packages
  apt:
    name: "{{packages}}"
    state: absent
  vars:
    packages:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: (Deian) install required packages
  apt:
    name: "{{packages}}"
    state: present
  vars:
    packages:
    - apt-transport-https

- name: (Deian) add docker apt key"
  apt_key:
    url: https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg
    state: present

- name: (Deian) add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution | lower}} {{ansible_distribution_release}} stable
    filename: docker
    state: present

- name: (Deian) install containerd
  apt:
    name: containerd.io
    state: present
    update_cache: yes
  notify: restart_containerd
