metrics_server_version: master          # v0.3.1
metrics_server_namespace: kube-system   # kube-metrics
metrics_server_manifest_base_url: https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/{{metrics_server_version}}/deploy/1.8+
