---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: selfsigning-issuer
spec:
  selfSigned: {}
---
##### Example #####
# apiVersion: certmanager.k8s.io/v1alpha1
# kind: Certificate
# metadata:
#   name: example-crt
# spec:
#   secretName: selfsigned-cert
#   commonName: selfsigned-root-ca
#   isCA: true
#   issuerRef:
#     name: selfsigning-issuer
#     kind: ClusterIssuer
