---
- name: (Deian) install required packages
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https

- name: (Deian) add kubernetes apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: (Deian) add kubernetes apt repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes
    state: present

- name: (Deian) install kubectl
  apt:
    name:  kubectl
    state: present
    update_cache: yes
