apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  rules:
  - host: demos.k8s.teko.vn
    http:
      paths:
      - backend:
          serviceName: kubernetes-bootcamp
          servicePort: 8080
