---
- name: config kernel moduel
  copy:
    src:  modules.conf
    dest: /etc/modules-load.d/modules.conf
  notify: reload_kernal_modules

- name: config sysctl
  copy:
    src:  99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
  notify: reload_sysctl

- name: config crictl
  copy:
    src:  crictl/{{kubernetes_cri}}.yaml
    dest: /etc/crictl.yaml

- name: install bash-completion
  package:
    name: bash-completion
    state: present

- name: add kubernetes bash_completion
  copy:
    src:  'kube-completions.sh'
    dest: '/etc/profile.d/'
    mode: '0644'

- name: remove swapfile from /etc/fstab
  replace:
    path:    '/etc/fstab'
    regexp:  '^(/\S+\s+none\s+swap\s+.*)'
    replace: '# \1'

- name: disable swap
  command: swapoff -a
  ignore_errors: yes
