kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-node
spec:
  template:
    spec:
      containers:
      - name: calico-node
        env:
        - name: CALICO_IPV4POOL_CIDR
          value: "{{calico_pod_cidr}}"
