---
- name: (RedHat) remove old packages
  yum:
    name: "{{packages}}"
    state: absent
  vars:
    packages:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine

- name: (RedHat) add docker yum repository
  get_url:
    url: https://download.docker.com/linux/{{ansible_distribution | lower}}/docker-ce.repo
    dest: /etc/yum.repos.d
    mode: u=rw,g=r,o=r

- name: (RedHat) install docker-ce
  yum:
    name: docker-ce
    state: present
    enablerepo: docker-ce-{{docker_channel}}
  notify: enable_docker

- name: (RedHat) add users to docker group
  user:
    name: "{{username}}"
    groups: docker
    append: yes
  loop: "{{docker_users}}"
  loop_control:
    index_var: username
