- hosts: elastic_nodes
  become: true
  roles:
    - role: elastic.elasticsearch
  vars:
    es_instance_name: "product_list"
    es_heap_size: "2g"
    es_config:
      cluster.name: "listing-cluster"
      discovery.zen.ping.unicast.hosts: ["listing-stg1.teko.vn","listing-stg2.teko.vn"]
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: true
      network.host: "0.0.0.0"
      http.host: "0.0.0.0"
      bootstrap.memory_lock: false
    es_xpack_features: []
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_plugins:
      - plugin: ingest-geoip
